We will be evaluating a number of classification models on the UCI dataset of Breast Cancer Research

Importing Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Importing the dataset

In [ ]:
dataset= pd.read_csv('Data.csv')
X= dataset.iloc[:, :-1].values
y= dataset.iloc[:, -1].values

Splitting the dataset into train and test sets

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=0.2, random_state=0)

Scaling the dataset

In [ ]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)

Training the logistic regression model

In [ ]:
from sklearn.linear_model import LogisticRegression
lr= LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression()

Training the KNN classifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier(n_neighbors=5, metric= 'minkowski', p=2)
knn.fit(X_train, y_train)

KNeighborsClassifier()

Training the Kernel SVM model

In [ ]:
from sklearn.svm import SVC
svc= SVC(kernel= 'rbf', random_state=0)
svc.fit(X_train, y_train)

SVC(random_state=0)

Training the naive bayes model

In [ ]:
from sklearn.naive_bayes import GaussianNB
nb= GaussianNB()
nb.fit(X_train, y_train)

GaussianNB()

Training the Decision Tree Classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt= DecisionTreeClassifier(criterion='entropy', random_state=0)
dt.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

Training the Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf= RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
rf.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

Evaluating Performance of all the models

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score
#Logistic Regression
y_pred= lr.predict(X_test)
cm= confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))
print(f1_score(y_test, y_pred, pos_label= 4))

[[84  3]
 [ 3 47]]
0.9562043795620438
0.94


In [ ]:
#KNN Classifier
y_pred= knn.predict(X_test)
cm= confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))
print(f1_score(y_test, y_pred, pos_label= 4))

[[83  4]
 [ 2 48]]
0.9562043795620438
0.9411764705882353


In [ ]:
#Kernel SVM
y_pred= svc.predict(X_test)
cm= confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))
print(f1_score(y_test, y_pred, pos_label= 4))

[[82  5]
 [ 1 49]]
0.9562043795620438
0.9423076923076924


In [ ]:
#Naive Bayes
y_pred= nb.predict(X_test)
cm= confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))
print(f1_score(y_test, y_pred, pos_label= 4))

[[80  7]
 [ 0 50]]
0.948905109489051
0.9345794392523363


In [ ]:
#Decision Tree Classifier
y_pred= dt.predict(X_test)
cm= confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))
print(f1_score(y_test, y_pred, pos_label= 4))

[[85  2]
 [ 2 48]]
0.9708029197080292
0.96


In [ ]:
#Random Forest Classifier
y_pred= rf.predict(X_test)
cm= confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))
print(f1_score(y_test, y_pred, pos_label= 4))

[[84  3]
 [ 3 47]]
0.9562043795620438
0.94


As seen by the results, Decision Tree Classifier achieves the highest accuracy and F1 score on the dataset used